/*******************************************************************************************************
* @Name         : TPM_TriggerException
* @unit Test    : 
* @author       : PwC Team
* @date         : 12/09/2022
* @description  : Trigger Exception class
*******************************************************************************************************/
public inherited sharing class TPM_TriggerException extends Exception {
    
    //Exception variable
    private static boolean isExcep = true;
}